---


iptables_config: |
  *filter  

  :INPUT DROP [0:0]
  :FORWARD DROP [0:0]
  :OUTPUT ACCEPT [0:0]
  # --- Allow unrestricted traffic on a few local network adapters.
  -A INPUT -i lo -j ACCEPT
  -A INPUT -i eth1 -j ACCEPT
  -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT  

  # --- Allow the outside world to connect to SSH (22), HTTP (80) and HTTPS (443).
  -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
  -A OUTPUT -p tcp -m tcp --dport 22 -j ACCEPT
  -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
  -A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
  -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
  -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
  -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT
  -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
  -A OUTPUT -o lo -j ACCEPT  
  -A INPUT -p icmp -m icmp --icmp-type echo-request -j DROP
  -A OUTPUT -p icmp -m icmp --icmp-type echo-reply -j DROP
  -A OUTPUT -p icmp -m icmp --icmp-type echo-request -j DROP 

  COMMIT

